project:
  type: book
  output-dir: laboratorios_pdf

book:
  title: "Apuntes y Laboratorios de Optimización y Análisis de Redes"
  author: 
    - "Víctor Aceña Gil"
    - "Emilio López Cano"
    - "Javier Martínez Moguerza"
  chapters:
    - index.qmd
    - 01_intro_opt.qmd
    - 02_opt_sin_rest.qmd
    - 03_analisis_convexo.qmd
    - 04_opt_con_rest.qmd
    - 05_aplicaciones_kkt.qmd
    - 06_opt_ciencia_datos.qmd
    - 07_intro_redes.qmd
    - 08_camino_minimo.qmd
    - 09_problemas_flujo.qmd
    - 10_emparejamiento.qmd
    - 11_problemas_recorridos.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    css: ../estilos_html.css
  pdf:
    documentclass: scrreprt
    title-block-banner: false 
    toc: true
    toc-depth: 3
    toc-title: "Índice de Contenidos"
    number-sections: true
    keep-tex: false
    include-in-header:
      text: |
        \usepackage{xcolor}
        \usepackage{tcolorbox}
        \tcbuselibrary{skins, breakable}
        \usepackage{framed}
        
        % Entorno para prácticas en LaTeX
        \definecolor{practicabg}{RGB}{255, 250, 240}
        \definecolor{practicaborder}{RGB}{255, 165, 0}
        \newtcolorbox{rmdpractica}{
          colback=practicabg,
          colframe=practicaborder,
          boxrule=1pt,
          arc=3pt,
          left=6pt,
          right=6pt,
          top=6pt,
          bottom=6pt,
          title={\textbf{Práctica:}},
          fonttitle=\bfseries
        }
        
        % Entorno para información útil en LaTeX
        \definecolor{infobg}{RGB}{240, 248, 255}
        \definecolor{infoborder}{RGB}{70, 130, 180}
        \newtcolorbox{rmdinfo}{
          colback=infobg,
          colframe=infoborder,
          boxrule=1pt,
          arc=3pt,
          left=6pt,
          right=6pt,
          top=6pt,
          bottom=6pt,
          title={\textbf{Nota Informativa:}},
          fonttitle=\bfseries
        }
